# Generated by Django 3.1.4 on 2020-12-12 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_tovar_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(max_length=30)),
                ('is_ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='tovars_in_purchase',
            name='tovar',
        ),
        migrations.RemoveField(
            model_name='tovars_in_purchase',
            name='users_purchase',
        ),
        migrations.RemoveField(
            model_name='users_purchase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='users_purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tovar',
            name='category',
        ),
        migrations.AddField(
            model_name='tovar',
            name='category',
            field=models.CharField(choices=[('Milk', 'Молочная продукция'), ('Honey', 'Мёд'), ('Meat', 'Мясо'), ('Egg', 'Яйца птицы'), ('Plant', 'Растительный продукт')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tovar',
            name='slug',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Tovars_in_purchase',
        ),
        migrations.DeleteModel(
            name='Users_purchase',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tovar'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='tovars',
            field=models.ManyToManyField(to='users.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
