# Generated by Django 3.1.4 on 2020-12-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_orderitem_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='slug',
            field=models.SlugField(),
        ),
    ]
