# Generated by Django 3.1.4 on 2020-12-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201223_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
