# Generated by Django 3.1.4 on 2020-12-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201223_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
